package reverseVowelsOfString;

public class Solution2 {
	// generated by AI

	public String reverseVowels(String s) {
		char[] chars = s.toCharArray();
		int left = 0, right = chars.length - 1;
		while (left < right) {
			if (!isVowel(chars[left])) {
				left++;
			} else if (!isVowel(chars[right])) {
				right--;
			} else {
				char temp = chars[left];
				chars[left] = chars[right];
				chars[right] = temp;
				left++;
				right--;
			}
		}
		return new String(chars);
	}

	private boolean isVowel(char c) {
		return "aeiouAEIOU".indexOf(c) != -1;
	}

	public static void main(String[] args) {
		Solution2 test = new Solution2();
		System.out.println(test.reverseVowels("CreAtive"));
	}

}
